# Config file for automatic testing at travis-ci.org

language: python

before_script:
  - sudo apt-get install openjdk-7-jre

python:
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt --use-mirrors

# command to run tests, e.g. python setup.py test
script: make test
