#!/usr/bin/env bash
wget -c http://dynamodb-local.s3-website-us-west-2.amazonaws.com/dynamodb_local_2015-04-27_1.0.tar.gz -O /tmp/dynamodb_local.tar.gz
rm -rf /tmp/dynamodb
mkdir /tmp/dynamodb
tar -xvf /tmp/dynamodb_local.tar.gz -C /tmp/dynamodb
DYNAMODB_PATH=`mktemp -d`
java -Djava.library.path=/tmp/dynamodb/DynamoDBLocal_lib -jar /tmp/dynamodb/DynamoDBLocal.jar -dbPath "$DYNAMODB_PATH" > "$DYNAMODB_PATH/daynamodb.log" &
DYNAMODB_PID="$!"
echo $DYNAMODB_PID
{
    python setup.py test
} || {
    kill "$DYNAMODB_PID"
    exit 1;
}

kill "$DYNAMODB_PID"
rm -rf $DYNAMODB_PATH